server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: tax-filing-service
              uri: lb://tax-filing-service
              predicates:
                - Path=/tax-filing-service/**
              filters:
                - StripPrefix=1
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/payment-service/**
              filters:
                - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: api-gateway
    instance-id: ${spring.application.name}:${server.port}