apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-payment-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-payment
  template:
    metadata:
      labels:
        app: postgres-payment
    spec:
      containers:
        - name: postgres-payment
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: paymentdb
            - name: POSTGRES_USER
              value: paymentuser
            - name: POSTGRES_PASSWORD
              value: paymentpass
          volumeMounts:
            - name: payment-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: payment-storage
          persistentVolumeClaim:
            claimName: postgres-payment-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-payment
spec:
  type: ClusterIP
  selector:
    app: postgres-payment
  ports:
    - port: 5432
      targetPort: 5432
