pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds')
        IMAGE_NAME = 'vinay564/ai-assistant-service'
        KUBECONFIG = '/var/jenkins_home/.kube/config'
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/vinay564/tax-filing-microservices.git'
            }
        }
        stage('Build Image') {
            steps {
                dir('ai-assistant-service') {
                    sh 'docker build -t $IMAGE_NAME:1.0 .'
                }
            }
        }
        stage('Push to Docker Hub') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                sh 'docker push $IMAGE_NAME:1.0'
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl rollout restart deployment/ai-assistant-service'
                sh 'kubectl rollout status deployment/ai-assistant-service --timeout=120s'
            }
        }
    }
}